#---------------------------------------
macro(IK_SetupProject MODE TARGET_NAME STR_TARGET_SOURCES STR_TARGET_LIBS)
    IK_PackageName(package_name)
    string(REPLACE " " ";" LIST_TARGET_SOURCES ${STR_TARGET_SOURCES})
    string(REPLACE " " ";" LIST_TARGET_LIBS ${STR_TARGET_LIBS})
    if(COMMAND cmake_policy)
    cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)
    if(${STR_TARGET_SOURCES} STREQUAL " ")
        message(WARNING "Target [${TARGET_NAME}] has no source, so it won't be generated.")
    else()
        if(${MODE} STREQUAL "EXE")
            add_executable( ${TARGET_NAME} ${LIST_TARGET_SOURCES})
            set(INSTALL_DIR "bin")
            install (TARGETS ${TARGET_NAME} DESTINATION ${INSTALL_DIR})
        elseif(${MODE} STREQUAL "LIB")
            add_library(${TARGET_NAME} ${LIST_TARGET_SOURCES})
            #set(INSTALL_DIR "lib/Gen")
        else()
            message(FATAL_ERROR "Mode [${MODE}] is not supported, so target [TARGET_NAME] is not generated!")
            set(MODE_NOTSUPPORT " ")
        endif()
        if(NOT DEFINED MODE_NOTSUPPORT)
            if( NOT ${FOLDER_NAME} STREQUAL " ")
                SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES FOLDER ${FOLDER_NAME})
            endif()
            if(NOT ${STR_TARGET_LIBS} STREQUAL " ")
                target_link_libraries( ${TARGET_NAME} ${LIST_TARGET_LIBS} )
            endif()
            install(TARGETS ${targetName}
                EXPORT "${PROJECT_NAME}Targets"
                RUNTIME DESTINATION "bin"
                ARCHIVE DESTINATION "${package_name}/lib"
                LIBRARY DESTINATION "${package_name}/lib"
            )
            message(STATUS "Setup Target ${FOLDER_NAME}/[${TARGET_NAME}] success")
        endif()
    endif()
endmacro(IK_SetupProject TARGET_NAME STR_TARGET_SOURCES STR_TARGET_LIBS)
